### ISSUE TITLE
Inserting text into the editor

### ISSUE THREAD

**Issue by swastik** [bustlelabs/ember-mobiledoc-editor#113]
First of all, thanks for the great work on this plugin! 😀

I was wondering if there's a way to insert text into the editor from the outside. I'm working on a feature that allows users to insert some arbitrary text by clicking on something that's outside the editor.

I tried working with the `innerHTML` property (i.e. appending to the editor by modifying its `innerHTML`) but that doesn't quite get it right. It will insert it goes out of sync; deleting that text is impossible.

Any ideas?

**Comment by bantic** [comment]
@swastik You're welcome! :)

Yeah, you should be able to use the editor's API directly, after you've rendered it. The `{{ember-mobiledoc-editor}}` component will fire an action when the editor is created. You can use that action to grab a reference to the editor and then later modify the mobiledoc post in reaction to some other event.

Here's an example, with the application controller and template
```
{{! templates/application.hbs}}
{{mobiledoc-editor did-create-editor=(action 'didCreateEditor')}}

<button {{action 'insertText'}}>Insert text into the editor</button>
```

```javascript
// controllers/application.js
// ...
export default Ember.Controller.extend({
  actions: {
    didCreateEditor(editor) {
      // keep a reference to the mobiledoc-kit editor
      this._editor = editor;
    },
    insertText() {
      // this action is called when the person clicks the button
      if (!this._editor) { return; } // can't do anything if the editor hasn't been created yet
      this._editor.insertText('some text...');
    }
  }
});
```

You can check [the docs for editor#insertText here](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/Editor.html#insertText).

**Note** that `insertText` doesn't do anything if the editor doesn't have an active cursor in it. If you want to insert text when the editor doesn't have focus you can use the [postEditor's `insertText` hook](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/PostEditor.html#insertText), which accepts a position. So for example you could do this:
```javascript
editor.run(postEditor => {
  let tail = editor.post.tailPosition(); // insert at end
  postEditor.insertText(tail, 'some text at the end...');
});
```

I'll close this as I think this addresses your question, but please reopen if you have any other questions! Thanks!

**Comment by bantic** [comment]
I created a sample repo here: https://github.com/bantic/try-mobiledoc-editor
If you want to see the diff it is at: https://github.com/bantic/try-mobiledoc-editor/commit/d10a7f4d102394a239ce8e5f5e60935c9ce73f50
Hope that helps :)

**Comment by swastik** [comment]
@bantic — Thank you so much! It does work. Thanks once again for your work on this library! 😀

**Comment by Niranjan24491** [comment]
the above code doesn't seem to work for my scenario. I have included the ember-mobiledoc-editor with a toolbar. I have an external dropdown which on click i'm trying to update that value to the text-editor which is throwing me errors with isMarkerable and marker internally. Please let me know if i'm doing anything wrong.

`editor.run(postEditor => {
      let tail = editor.post.tailPosition(); // insert at end
      postEditor.insertText(tail, ' {' + item.value + '} ');
    });`

this code is executed on change of the dropdown value

hbs is as follows

`  {{#mobiledoc-editor did-create-editor=(action 'didCreateEditor')
    as |editor|}}
      <div class="rtf-toolbar">
        <div class="toolbar-container">
          {{#mobiledoc-markup-button editor=editor for="b"}}
            <b>B</b>
          {{/mobiledoc-markup-button}}
          {{#mobiledoc-markup-button editor=editor for="i"}}
           <i>I</i>
          {{/mobiledoc-markup-button}}
          {{#mobiledoc-markup-button editor=editor for="u"}}
            <u>U</u>
          {{/mobiledoc-markup-button}}
        </div>
      </div>
  {{/mobiledoc-editor}}`

**Comment by Niranjan24491** [comment]
the above code doesn't seem to work for my scenario. I have included the ember-mobiledoc-editor with a toolbar. I have an external dropdown which on click i'm trying to update that value to the text-editor which is throwing me errors with isMarkerable and marker internally. Please let me know if i'm doing anything wrong.

js
```
editor.run(postEditor => {
  let tail = editor.post.tailPosition(); // insert at end
  postEditor.insertText(tail, 'some text at the end...');
});
```
this code is executed on change of the dropdown value

hbs

```
  {{#mobiledoc-editor did-create-editor=(action 'didCreateEditor')
    as |editor|}}
      <div class="rtf-toolbar">
        <div class="toolbar-container">
          {{#mobiledoc-markup-button editor=editor for="b"}}
            <b>B</b>
          {{/mobiledoc-markup-button}}
          {{#mobiledoc-markup-button editor=editor for="i"}}
           <i>I</i>
          {{/mobiledoc-markup-button}}
          {{#mobiledoc-markup-button editor=editor for="u"}}
            <u>U</u>
          {{/mobiledoc-markup-button}}
        </div>
      </div>
  {{/mobiledoc-editor}}
```
