### ISSUE TITLE
Combining Component Cards with the default cardsList

### ISSUE THREAD

**Issue by kbhardwaj** [bustlelabs/ember-mobiledoc-editor#32]
I've been getting to know the mobiledoc-kit for the past couple days and am really loving it! Thanks for building this, it's so much better than attempting to roll my own contenteditable text areas. 

I've been able to create my own Component Cards, but I'm now trying to add the component card to the default cardsList:

 ```javascript
    import Ember from 'ember';
    import createComponentCard from 'ember-mobiledoc-editor/utils/create-component-card';
    import { cardsList } from '../mobiledoc-cards/index';

    // Combining Component Card with the default cardsList
    export default Ember.Component.extend({
        cards: Ember.computed(function() {
            return [
                createComponentCard('demo-card'),
                cardsList
            ];
        })
    });
```

Here I get an error `Uncaught Error: Unknown card encountered: image-card` when trying to add an image card. 

What would be the correct way of doing this?

**Comment by kbhardwaj** [comment]
sorry, figured it out. this worked:

```javascript
import Ember from 'ember';
import createComponentCard from 'ember-mobiledoc-editor/utils/create-component-card';
import { cardsList } from '../mobiledoc-cards/index';

// Combining Component Cards with the default cardsList
export default Ember.Component.extend({
  cards: Ember.computed(function() {
  	cardsList.push(createComponentCard('demo-card'))
  	return cardsList
  })
});
```

**Comment by mixonic** [comment]
@kbhardwaj we actually do this with a helper in an app codebase, making it easy to pass:

```hbs
{{mobiledoc-editor cards=(mobiledoc-cards) mobiledoc=someMobiledoc}}`
```

without needing to make a property on the component providing context. I sense there is a better way we could do this for the 90% case.
