### ISSUE TITLE
outdated broccoli-funnel

### ISSUE THREAD

**Issue by stefanpenner** [bustlelabs/ember-mobiledoc-editor#55]
https://github.com/bustlelabs/ember-mobiledoc-editor/blob/master/package.json#L47 because performance: https://github.com/broccolijs/broccoli-funnel/pull/44

Upgrade should be pretty simple, the API didn't really change, just some things tightened up

**Comment by bantic** [comment]
thanks for the note! upgraded :)

**Comment by stefanpenner** [comment]
:+1:
