### ISSUE TITLE
Best strategy for migrating existing content?

### ISSUE THREAD

**Issue by atonse** [bustlelabs/ember-mobiledoc-editor#77]
Mobiledoc Editor looks awesome (especially cards), and I want to use it on my Ember app. Even though it's a green field app, there is existing content in my database in the field (`project.description`) in which I want to use the Mobiledoc editor. 

So right now when I edit a Project, the Mobiledoc editor crashes because the "existing" value is not valid Mobiledoc. 

I'm thinking my best option is to convert the existing text/html to Mobiledoc format. Is there already a converter or do I have to roll my own?

Or is there another option I can use that will transparently do this the _first_ time the doc is edited?

**Comment by bantic** [comment]
@atonse The MobiledocKit editor accepts an `html` option instead of `mobiledoc`, in which case it parses the html (lossily, since not everything in html translates into mobiledoc). This isn't well-exposed through this addon (the `{{ember-mobiledoc-editor}}` expects to receive a `mobiledoc` property only), but you could parse the HTML in your own app code before passing it to the editor like so:

```
import MobiledocKit from 'mobiledoc-kit';
let editor = new Editor({html: yourHTML});
let mobiledoc = editor.serialize();
```

**Comment by atonse** [comment]
@bantic Great! Thank you – I could modify the readme to just add this side note (as I assume a lot of people probably hit this?) – worth doing? I can submit a PR.

**Comment by bantic** [comment]
Yes, that would be appreciated, thank you! Could you also add an issue for
allowing an `html` option to be passed to the `{{ember-mobiledoc-editor}}`
component?

On Tue, Apr 19, 2016 at 11:46 AM, Ashish Tonse <notifications@github.com>
wrote:

> @bantic <https://github.com/bantic> Great! Thank you – I could modify the
> readme to just add this side note (as I assume a lot of people probably hit
> this?) – worth doing? I can submit a PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bustlelabs/ember-mobiledoc-editor/issues/77#issuecomment-211987935>
>



-- 
http://twitter.com/bantic

**Comment by atonse** [comment]
@bantic sure – will get on this later today. Thanks again.
