### ISSUE TITLE
Auto-expanding the editing area to a max height

### ISSUE THREAD

**Issue by atonse** [bustlelabs/ember-mobiledoc-editor#84]
Thanks for this great add-on. This approach seems more robust than using TinyMCE, etc.

Is there a plan to add autosizing functionality to the component so it expands to a max of X lines/pixels, and becomes scrollable after that? I'm happy to work on this and submit a PR but didn't want to create duplicate work if it's already part of your near-term roadmap.

Currently when I add more text, it just flows off the component surface (example attached).
<img width="282" alt="screen shot 2016-05-04 at 3 39 20 pm" src="https://cloud.githubusercontent.com/assets/6015/15026841/6aedd15a-120e-11e6-8530-d6a67462d198.png">

**Comment by patrickberkeley** [comment]
@atonse I haven't tested it with `ember-mobile-doc` but [`ember-autoresize`](http://tim-evans.github.io/ember-autoresize/) is great for dynamically resized textareas and inputs.

**Comment by atonse** [comment]
@patrickberkeley I can try it but this component generates a `div` and not a `textarea`. The weird part is that the widget expands in the demo site. So this might be an issue on my side.

**Comment by atonse** [comment]
@patrickberkeley Closing this issue – I had a CSS rule that was preventing my editor from expanding vertically. Sorry about that!
